/** @type {import('tailwindcss').Config} */
import { nextui } from "@nextui-org/react";
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./app/**/*.{js,jsx}",
    "./src/**/*.{js,jsx}",
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        'custom-text': {
          50: '#13070c',
          100: '#250e18',
          200: '#4b1b30',
          300: '#702948',
          400: '#963660',
          500: '#bb4478',
          600: '#c96993',
          700: '#d68fae',
          800: '#e4b4c9',
          900: '#f1dae4',
          950: '#f8ecf1',
        },
        'custom-background': {
          50: '#13060b',
          100: '#260d15',
          200: '#4d192a',
          300: '#732640',
          400: '#993355',
          500: '#bf406a',
          600: '#cc6688',
          700: '#d98ca6',
          800: '#e6b3c3',
          900: '#f2d9e1',
          950: '#f9ecf0',
        },
        'custom-primary': {
          50: '#1a0009',
          100: '#330013',
          200: '#660025',
          300: '#990038',
          400: '#cc004b',
          500: '#ff005d',
          600: '#ff337e',
          700: '#ff669e',
          800: '#ff99be',
          900: '#ffccdf',
          950: '#ffe5ef',
        },
        'custom-secondary': {
          50: '#1a000a',
          100: '#330014',
          200: '#660029',
          300: '#99003d',
          400: '#cc0052',
          500: '#ff0066',
          600: '#ff3385',
          700: '#ff66a3',
          800: '#ff99c2',
          900: '#ffcce0',
          950: '#ffe5f0',
        },
        'custom-accent': {
          50: '#000d1a',
          100: '#001a33',
          200: '#003566',
          300: '#004f99',
          400: '#0069cc',
          500: '#0084ff',
          600: '#339cff',
          700: '#66b5ff',
          800: '#99ceff',
          900: '#cce6ff',
          950: '#e5f3ff',
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), nextui()],
};
